"""Add notes table

Revision ID: 038940d2e0aa
Revises: 92ef8f25350e
Create Date: 2025-06-11 04:15:08.883877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038940d2e0aa'
down_revision = '92ef8f25350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_restaurants',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_restaurants')
    op.drop_table('collection')
    # ### end Alembic commands ###
