"""Add profile_image to User model

Revision ID: 06a81e0a8559
Revises: 2a505c428060
Create Date: 2025-06-09 23:24:08.851423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a81e0a8559'
down_revision = '2a505c428060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('restaurant_image')
#     op.drop_table('favourites')
    with op.batch_alter_table('operating_hour', schema=None) as batch_op:
        batch_op.alter_column('open_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('close_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.drop_constraint('uq_restaurant_day', type_='unique')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cuisine_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('Maps_link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('price')
        batch_op.drop_column('cuisine')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('date_joined')
        batch_op.drop_column('location')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('Maps_link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('cuisine_type')
        batch_op.drop_column('price_range')
        batch_op.drop_column('website')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('operating_hour', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_restaurant_day', ['restaurant_id', 'day_of_week'])
        batch_op.alter_column('close_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('open_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    op.create_table('favourites',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('restaurant_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=300), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
