"""Add is_24_hours to Restaurant

Revision ID: 2a505c428060
Revises: bb9109af4b0d
Create Date: 2025-06-09 22:37:24.695776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a505c428060'
down_revision = 'bb9109af4b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operating_hour', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_restaurant_day', ['restaurant_id', 'day_of_week'])

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_24_hours', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('is_24_hours')

    with op.batch_alter_table('operating_hour', schema=None) as batch_op:
        batch_op.drop_constraint('uq_restaurant_day', type_='unique')

    # ### end Alembic commands ###
