"""Add latitude and longitude to restaurant

Revision ID: a38d9a65974e
Revises: b7dc1a12fb1d
Create Date: 2025-05-18 20:33:17.695261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d9a65974e'
down_revision = 'b7dc1a12fb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
