"""Rename Maps_link to Maps_link

Revision ID: bb9109af4b0d
Revises: c5d87415236c
Create Date: 2025-05-28 02:35:12.688634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9109af4b0d'
down_revision = 'c5d87415236c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Maps_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('rating')
        batch_op.drop_column('google_maps_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_maps_link', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('Maps_link')

    # ### end Alembic commands ###
