"""Added new columns to Restaurant

Revision ID: cef0c6ae8754
Revises: 
Create Date: 2025-05-10 00:26:19.971718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef0c6ae8754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_maps_link', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('google_maps_link')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    with op.batch_alter_table('my_admin', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
